### ISSUE TITLE
Have multiple apt repositories for development

### ISSUE THREAD

**Issue by celskeggs** [sipb/homeworld#168]
Currently, we only have one, which gets used both for mainline packages and testing packages. We need an easy way to have multiple and switch between them.

**Comment by krawthekrow** [comment]
Instead of multiple repositories, we could use multiple suites in the same repository:

- [ ] Currently homeworld-apt-setup, homeworld-knc and homeworld-keysystem are manually downloaded and integrated into the ISO by Spire, and installed at post-install. We could do this only for homeworld-apt-setup, and do apt-get update/upgrade/install during post-install. (iso.py, postinstall.sh)
- [ ] Add a switch to select which suite to install from in infra install-packages and affected seq commands. (infra.py, seq.py)
- [ ] Add a switch for upload-debs/rebuild.sh to specify which suite we're building for.
- [ ] Create the testing suite.
- [ ] Add the testing suite to homeworld.sources.

Does this sound like a reasonable approach?

**Comment by andersk** [comment]
I don’t think you want testing to require bits on the same repository that serves prod—that’s going to make development inconvenient and might lead to accidents on prod.

**Comment by celskeggs** [comment]
Agreed with andersk. We probably want to have actual different `apt` repositories, not just different suites.

Also, having just "prod" and "testing" would miss the point. The point is to be able to have arbitrary numbers of repositories -- "prod", "mtheng-1", "cela-trying-out-new-etcd", et cetera.

**Comment by krawthekrow** [comment]
Including packages other than apt-setup in the ISO would require having to set the apt repository source in two places -- in homeworld-apt-setup and in Spire. Here's a proposal for multiple apt repositories:

- [ ] Create and document a process flow for creating a personal homeworld-apt-setup deb.
- [ ] As above, only copy in homeworld-apt-setup when generating the ISO, and update/upgrade/install in post-install.
- [ ] Add a switch to iso.py that chooses whether to download the prod homeworld-apt-setup deb or use the locally built one.
- [ ] Add configuration for upload-debs/rebuild.sh.

**Comment by celskeggs** [comment]
I would consider the following set of changes:

- [ ] Split out the `/building/build-debs/binaries/` folder into multiple variants, one for each apt branch.
- [ ] Require specifying which apt branch we're building for, whenever we build a package. This lets the `homeworld-apt-setup` package and the `homeworld-admin-tools` package know which apt branch is in use.
- [ ] In `upload-debs/rebuild.sh`, require specifying which apt branch we're rebuilding, and (optionally) another branch to use for all packages not built for this specific branch.

The difference here is that binaries are built for a specific branch, so it's harder to accidentally cross-contaminate branches by building different packages locally.

Additional changes:

- [ ] Add a mechanism to generate signing keys for each apt branch, and incorporate the public keys in locations like homeworld-apt-setup.
- [ ] Change the folder structure of `/mit/hyades/debian` to `/mit/hyades/apt/<username>/<branch>`, for the sake of privilege separation.

**Comment by celskeggs** [comment]
@krawthekrow: what are your opinions on my variation on your design?

**Comment by krawthekrow** [comment]
Sounds good, I'll give it a shot.

**Comment by celskeggs** [comment]
I've created `/mit/hyades/apt/{mtheng,root,cela}`. You should have access to `/mit/hyades/apt/mtheng`, which is hopefully enough for testing.
