### ISSUE TITLE
Cannot reproduce kubernetes source archive

### ISSUE THREAD

**Issue by ichung** [sipb/homeworld#236]
Somewhere between git versions 2.1.4 (what was used to create the archive in homeworld-upstream) and  and 2.11.0 (which I used to reproduce it), the handling of git placeholders (see gitattributes(5)) changed slightly in the format of commit hashes, causing different archives to be created.  In particular, this causes differences like

    -       gitVersion   string = "v1.8.0+0b9efae"
    +       gitVersion   string = "v1.8.0+0b9efaeb34"

to result in the archive.  We should find a way of reliably recreating the same source archive.

**Comment by celskeggs** [comment]
By using git-2.11.0 consistently, we've avoided this issue. We also now have scripts in place to prevent this from being a problem in the future, since verification is done for each PR automatically.

We should just add a check to make sure that the right version of git is being used in that script.

**Comment by celskeggs** [comment]
We no longer use homeworld-upstream, so this is now irrelevant.
