### ISSUE TITLE
Consider continuous integration

### ISSUE THREAD

**Issue by celskeggs** [sipb/homeworld#24]
~It would certainly be nice to have code be able to be pushed easily and smoothly, with canary nodes and automated rollback when things fail.~

It would be nice to get automatic notifications about builds passing and failing, and the associated independent verification of what built package hashes should be.

**Comment by celskeggs** [comment]
Continuous deployment seems like the wrong decision given the security properties we're trying to get out of Hyades.

Continuous integration is something to consider, but it's not clear how useful it will be, since it's hard to test Hyades without actually deploying to a set of servers.

**Comment by vulpicastor** [comment]
Integration testing of a cluster is... hard. Generally speaking, there are two strategies:

- run a separate dev cluster, and possibly also a staging server. The downside is that this increases SRE costs significantly, because there are three of everything running.
- cluster modeling, where you have a way of bringing up a toy cluster on a single machine, with each component `fork`ed instead of in its separate VM. Ideally, this environment is hermetic, so you can write integration tests against it in pretty much the same way that you write unit tests. The problem is that this requires us to have a terrifyingly awesome (read: Google-level) development infrastructure.

**Comment by andersk** [comment]
Is there anything that stops us from having a script that brings a toy cluster on a bunch of local VMs?

**Comment by celskeggs** [comment]
No, there isn't -- that's not even that much different from what we do to bring up our main dev cluster. You could probably follow the instructions in deploy.md and point things at a bunch of local VMs and have it work.

**Comment by celskeggs** [comment]
Update: we now have very simple CI, but it's limited to verifying reproducibility of our cache of upstream source code.

**Comment by celskeggs** [comment]
The rest of this has been rolled into #317.
