### ISSUE TITLE
Repackage the kubernetes dns-addon to use our own containers

### ISSUE THREAD

**Issue by celskeggs** [sipb/homeworld#32]
We use the kubernetes DNS addon, as seen in //deployment/clustered/dns-addon.yml.

This is a service that runs on the cluster itself and helps with resolution of certain cluster-specific domains.

One general policy of the Homeworld project is that, to the greatest extent possible, we do *not* trust binaries built by upstream projects -- only source code. We especially do not trust binaries hosted by third parties. Unfortunately, the docker ecosystem is based on fetching containers from untrusted third parties, and the dns addon is no exception.

We need to repackage the relevant containers (kubedns, kube-dnsmasq, exechealthz) so that they are:

 * built entirely from source code
 * with upstream code vendored in our upstream vendoring repository
 * with code verified through signed upstream sources if at all possible (or through HTTPS connections from multiple users if not)
 * built as ACI containers instead of docker containers
 * built using our existing container build infrastructure
 * uploaded and stored in our container registry with existing upload infrastructure

Once we do this, the dns addon will become significantly more trustworthy.

**Comment by celskeggs** [comment]
@coventry: How's this going? Am I correct in assuming that I should defer this to DC6, since it probably won't happen by this weekend?

**Comment by coventry** [comment]
Yes.

**Comment by coventry** [comment]
I think the repos with the relevant build systems are [dns](https://github.com/kubernetes/dns) and [contrib](https://github.com/kubernetes/contrib/) (which contains `extra-healthz`).

Both repos build the necessary container images (`kube-dns`, `sidecar`, `dnsmasq`, `exechealthz`) with a simple `make` command.

Why is it desirable to use homeworld's existing container build infrastructure, rather than converting the resulting docker images to ACI images using something like [`docker2aci`](https://github.com/appc/docker2aci)? The potential advantage of the conversion would be a simpler relationship to the upstream build systems: We just call `make` on our copies of the upstream repos, and any changes to their build logic would be run for us automatically.

**Comment by celskeggs** [comment]
In and of itself, using upstream's build systems and using docker2aci is reasonable, if a bit messy.

However, it looks like upstream depends on other containers (i.e. the alpine base image), which it's pulling from the docker repository during build, which is absolutely not okay. We'll need to patch the build process to have everything get built from source locally... at which point we sometimes may as well just rewrite the build script according to our needs. If you really want to find ways to patch the build process instead of rewriting it, you can give that a go.

**Comment by celskeggs** [comment]
This is depended on by #120, so we need to do it earlier.
