### ISSUE TITLE
Set up development chroots

### ISSUE THREAD

**Issue by celskeggs** [sipb/homeworld#363]
We need a stronger ability to support developers without powerful local machines. We should come up with a way to do this as a project -- either a dedicated server or something with a platform.

**Comment by celskeggs** [comment]
I will try to set up a development VM host by Friday (March 1st, 2019)

**Comment by celskeggs** [comment]
This is done! RHOMBI exists now.

**Comment by ichung** [comment]
We need VMs so that we can have independent installations of homeworld packages

**Comment by ichung** [comment]
In order to support concurrent deploys we have a couple things to do.  Ultimately we want to be able to do multiple autodeploys at once.  The problems with this are:

- only one version of spire can be installed
- autodeploy clobbers /etc/hosts
- IP addresses, hostnames, and network device names overlap if you're using the same config file

To solve the first two issues, every user will have their own chroot.  To solve the last issue, we need to make sure to use different IP addresses and hostnames.  One way to do this while keeping the shared config file would be to put a section in the config file for each user, and preprocess it into the actual config file used by spire.

**Comment by cryslith** [comment]
Closed by #381.
